In [1]:
# importing pytorch

import torch
torch.__version__

'2.10.0+cpu'

## Scalar, Vector, Matrix, and Tensor

In the context of deep learning and scientific computing, data is organized in hierarchical numerical structures. Understanding these structures is fundamental to working with frameworks like PyTorch.

- **Scalar**: A single numerical value with no dimensions (0-D). Mathematically, it belongs to a field such as ℝ. In PyTorch, a scalar tensor has `ndim = 0`. Example: a loss value after a training step.

- **Vector**: A one-dimensional ordered list of scalars (1-D array). Vectors represent features, embeddings, or bias terms in neural networks. A vector of length *n* belongs to ℝⁿ.

- **Matrix**: A two-dimensional rectangular array of scalars arranged in rows and columns (2-D). Matrices are central to linear transformations in neural networks — weight matrices in fully connected layers are of shape (input_features × output_features).

- **Tensor**: A generalization of scalars, vectors, and matrices to arbitrary dimensions (N-D). A tensor of rank *n* requires *n* indices to identify each element. Images are rank-3 tensors (height × width × channels), and batches of images are rank-4 tensors.

In [2]:
# creating scalar using tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
print(scalar.ndim)          # 0 — no dimensions
print(scalar.item())        # retrieves the Python number; only valid for single-element tensors
print(scalar.shape)         # torch.Size([]) — empty shape for scalars

0
7
torch.Size([])


In [4]:
# vector — a 1-D tensor
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [5]:
print(vector.ndim)    # 1
print(vector.shape)   # torch.Size([4])

1
torch.Size([4])


In [6]:
# Matrix — a 2-D tensor
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
print(matrix.ndim)    # 2
print(matrix.shape)   # torch.Size([3, 3])

2
torch.Size([3, 3])


In [8]:
# Tensor — 3-D and higher
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [9]:
print(TENSOR.ndim)    # 3
print(TENSOR.shape)   # torch.Size([1, 3, 3])

3
torch.Size([1, 3, 3])


## Random Tensors

Neural networks are initialized with **random weights** to break symmetry during training. If all weights were identical, every neuron in a layer would learn the same features — a phenomenon called the *symmetry problem*.

For reproducibility — essential when debugging or publishing experiments — a **random seed** is set using `torch.manual_seed(seed)`. This ensures the same sequence of random numbers is generated across runs.

In computer vision, a common tensor shape is **(H × W × C)** — height, width, and color channels. When processed in batches, it becomes **(N × H × W × C)**, where N is the batch size.

In [10]:
# randomize tensors
# Create a random tensor of size (2, 3) — uniform distribution
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.0279, 0.5943, 0.0754],
         [0.4974, 0.2427, 0.7695]]),
 torch.float32)

In [11]:
# Simulate an image tensor of shape (224, 224, 3) — H x W x C
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Creating Tensors of Zeros and Ones

Tensors filled with constant values are fundamental tools in deep learning:

- **`torch.zeros()`**: Creates a tensor where every element is `0.0`. Commonly used to initialize bias vectors, masks (e.g., zero out padding tokens), or to accumulate gradients.

- **`torch.ones()`**: Creates a tensor where every element is `1.0`. Used in residual connections, identity-like initializations, or scaling masks.

- **`torch.arange()`**: Generates a 1-D tensor with evenly spaced values in a half-open interval `[start, end)`, similar to Python's `range()`. Useful for position encodings in Transformer models or creating index sequences.

- **`torch.zeros_like()` / `torch.ones_like()`**: Creates a constant tensor matching the **shape and dtype** of a given tensor, without needing to explicitly specify dimensions. This is particularly useful when you want to create a zero tensor of the same shape as a weight matrix.

In [12]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [13]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [14]:
# Create a range of values 0 to 10 (exclusive)
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Create a tensor of zeros matching the shape of zero_to_ten
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

Choosing the correct **dtype** (data type) is a critical decision in deep learning, affecting both model accuracy and computational efficiency.


Most type-mismatch errors in PyTorch occur when tensors on different devices or of different dtypes are combined. Always verify these three attributes before performing operations.

In [16]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([2.0, 4.0, 6.0],
                               dtype=None,            # defaults to torch.float32
                               device=None,           # defaults to CPU
                               requires_grad=False)   # if True, tracks operations for autograd

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [17]:
# Explicitly create a float16 tensor (half-precision)
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)  # torch.half is an alias

float_16_tensor.dtype

torch.float16

## Getting Information from Tensors

Before performing any operation on a tensor, it is good practice to inspect its properties. PyTorch provides simple attributes to query the three fundamental tensor characteristics:

- **`.shape`**: Returns a `torch.Size` object describing the size of each dimension. For example, a tensor of shape `(3, 4)` has 3 rows and 4 columns.
- **`.dtype`**: Returns the data type of the tensor elements (e.g., `torch.float32`, `torch.int64`).
- **`.device`**: Returns the device the tensor resides on — `cpu` for RAM, or `cuda:0`, `cuda:1`, etc., for GPU memory.

Understanding these helps diagnose the most common runtime errors:
- **Shape mismatch** → matrix multiplication dimension errors
- **Dtype mismatch** → operations between integer and float tensors fail
- **Device mismatch** → cannot mix CPU and CUDA tensors in the same operation

In [18]:
# Create a random tensor and inspect its properties
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")  # defaults to CPU

tensor([[0.3177, 0.6011, 0.9424, 0.4160],
        [0.6632, 0.6329, 0.1211, 0.8839],
        [0.3485, 0.6790, 0.8933, 0.4187]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations

PyTorch supports a rich set of tensor operations that form the computational backbone of neural networks. These operations fall into two main categories:

### 1. Element-wise Operations
Operations applied independently to each corresponding pair of elements. Both tensors must have compatible shapes (either identical or broadcastable). Examples:
- Addition (`+`, `torch.add`)
- Subtraction (`-`, `torch.sub`)
- Multiplication (`*`, `torch.multiply`) — **not** matrix multiplication
- Division (`/`, `torch.div`)

### 2. Matrix Multiplication (Dot Product)
The **most important operation** in deep learning. In a fully connected layer, the forward pass computes:

$$\mathbf{y} = \mathbf{W} \cdot \mathbf{x} + \mathbf{b}$$

where **W** is the weight matrix and **x** is the input vector. This is performed using `torch.matmul()` or the `@` operator.

**Shape Rule for Matrix Multiplication**: For `A @ B`, the inner dimensions must match. If `A` has shape `(m, n)` and `B` has shape `(n, p)`, the result has shape `(m, p)`. When shapes don't align, use **transpose** (`.T`) to fix dimension order.

### Aggregate Operations
Used to reduce a tensor to a single summary value:
- `tensor.min()`, `tensor.max()` — minimum and maximum values
- `tensor.mean()` — arithmetic mean (requires float dtype)
- `tensor.sum()` — sum of all elements
- `tensor.argmin()`, `tensor.argmax()` — indices of min/max values (useful for classification outputs)

In [19]:
# Create a tensor of values and add a number to it (element-wise broadcast)
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [20]:
# Multiply by scalar — element-wise
tensor * 10

tensor([10, 20, 30])

In [21]:
tensor

tensor([1, 2, 3])

In [22]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [23]:
# Can also use torch functions directly
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

In [24]:
tensor

tensor([-9, -8, -7])

In [25]:
tensor = tensor + 10
# Element-wise multiplication: each index multiplies with itself
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
print("Equals:", torch.multiply(tensor, tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


In [26]:
# Contrast: element-wise vs matrix (dot product) multiplication
tensor = torch.tensor([1, 2, 3])

# Element-wise: [1*1, 2*2, 3*3] = [1, 4, 9]
print("Element-wise:", tensor * tensor)

# Dot product: 1*1 + 2*2 + 3*3 = 1 + 4 + 9 = 14
print("Dot product:", torch.matmul(tensor, tensor))

Element-wise: tensor([1, 4, 9])
Dot product: tensor(14)


In [27]:
# Shapes must be compatible for matmul
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)  # shape: (3, 2)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)  # shape: (3, 2)

# torch.matmul(tensor_A, tensor_B)  # ERROR: inner dims don't match (2 != 3)

In [28]:
# Fix with transpose: (3, 2) @ (2, 3) → valid, output shape = (3, 3)
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"After transpose: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} ← inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

After transpose: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) ← inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [29]:
# Aggregation operations
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")  # mean requires float dtype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [30]:
# argmax / argmin: returns the index of the maximum/minimum element
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")
print(f"Index where max value occurs: {tensor.argmax()}")  # useful in classification: index = predicted class
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [31]:
# Type casting: change dtype of a tensor
tensor = torch.arange(10., 100., 10.)
print("Original dtype:", tensor.dtype)

# Cast to float16 for memory-efficient computation
tensor_float16 = tensor.type(torch.float16)
tensor_float16

Original dtype: torch.float32


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [32]:
# Reshaping: change the shape without altering the data
import torch
x = torch.arange(1., 9.)
print(x, x.shape)

# Reshape to (1, 8): total elements must remain 8
x_reshaped = x.reshape(1, 8)
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [33]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [34]:
# view: like reshape but always shares memory with the original
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [35]:
z = x.view(2, 4)
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [36]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [37]:
# Demonstrating shared memory between view and original
# reshape may or may not share memory; view always does
x = torch.arange(6)

a = x.view(2, 3)      # shares memory — modifying a changes x
b = x.reshape(2, 3)   # may or may not share memory

a[0, 0] = 100
print(x)  # x is also changed because a shares memory with x

tensor([100,   1,   2,   3,   4,   5])


In [38]:
# torch.stack: creates a NEW dimension and concatenates tensors along it
# dim=0 stacks them as separate rows
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5]])

In [39]:
# dim=1 stacks them as separate columns
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[100, 100, 100, 100],
        [  1,   1,   1,   1],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5]])

In [40]:
# squeeze: removes all dimensions of size 1
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nAfter squeeze: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

# unsqueeze: adds a dimension of size 1 at the specified position
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nAfter unsqueeze(dim=0): {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

After squeeze: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])

After unsqueeze(dim=0): tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


In [41]:
# permute: reorders dimensions — commonly used to reformat image tensors
# e.g., convert from (H, W, C) → (C, H, W) for PyTorch's Conv2d
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("Original shape:", x.shape)  # (2, 3)

y = x.permute(1, 0)   # swap dim 0 and dim 1 → transpose

print(y)
print("Permuted shape:", y.shape)  # (3, 2)

Original shape: torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Permuted shape: torch.Size([3, 2])


## Indexing (Selecting Data from Tensors)

Indexing in PyTorch follows NumPy-style conventions and allows precise selection of elements, slices, or sub-tensors. This is essential when extracting batch samples, selecting specific channels, or isolating time steps in sequence data.


In [42]:
# Create a 3-D tensor and explore indexing levels
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

print(f"Full tensor (dim 0):\n{x[0]}")
print(f"Row 0 of dim 0: {x[0][0]}")
print(f"Element [0][0][0]: {x[0][0][0]}")

Full tensor (dim 0):
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Row 0 of dim 0: tensor([1, 2, 3])
Element [0][0][0]: 1


In [43]:
# Slice indexing
print(x[:, 0])      # all of dim 0, index 0 of dim 1 → first row of each matrix
print(x[:, :, 1])   # all of dims 0 and 1, index 1 of dim 2 → column 1 of each matrix
print(x[:, 1, 1])   # all of dim 0, element [1,1] of each matrix
print(x[0, 0, :])   # first matrix, first row, all columns

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


## PyTorch Tensors and NumPy Interoperability

PyTorch is designed to work alongside NumPy, the dominant library for scientific computing in Python. This interoperability is important because:

1. **Data preprocessing pipelines** often use NumPy (e.g., loading datasets, image transforms).
2. **Visualization libraries** such as Matplotlib and Seaborn expect NumPy arrays as input.
3. **Scikit-learn** models operate on NumPy arrays, so converting PyTorch outputs allows integration with classical ML evaluation tools.



In [44]:
# NumPy array to PyTorch tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)              # dtype: float64 (NumPy default)
tensor = torch.from_numpy(array)          # dtype: float64 preserved
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [45]:
# PyTorch tensor to NumPy array
tensor = torch.ones(7)                    # dtype: float32 (PyTorch default)
numpy_tensor = tensor.numpy()             # dtype: float32 preserved
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [46]:
# Check for GPU availability
import torch
torch.cuda.is_available()

False

In [47]:
# Device-agnostic setup: use GPU if available, else CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [48]:
# Count the number of available CUDA devices
torch.cuda.device_count()

0

In [49]:
# Create a tensor on CPU, then move it to GPU
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)        # shows: cpu

# Move to GPU (if available), otherwise stays on CPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [50]:
# To convert a GPU tensor to NumPy, first move it back to CPU
# tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
# tensor_back_on_cpu

## Discussion

This lab provided practical experience with PyTorch tensors and their fundamental operations. Key concepts explored included tensor dimensions, arithmetic operations, matrix multiplication, reshaping, indexing, and device management.

The exercises emphasized the importance of tensor shapes, data types, and memory behavior in deep learning applications. Understanding operations such as matrix multiplication, reshaping, and type casting is essential for building efficient neural networks. Additionally, the lab demonstrated PyTorch’s interoperability with NumPy and its ability to leverage GPU acceleration for improved computational performance.

Overall, the activities strengthened the foundational knowledge required for implementing and training deep learning models using PyTorch.


## Conclusion

This lab provided a practical introduction to PyTorch tensor operations, including tensor creation, manipulation, reshaping, indexing, arithmetic operations, and device management. The exercises reinforced the importance of understanding tensor shapes, ranks, data types, and memory behavior for efficient deep learning workflows.

Overall, the lab demonstrated that tensors are the core data structure in PyTorch and form the foundation of neural network computation. These fundamental skills will be essential for implementing and training neural networks in future labs.